### ISSUE TITLE
Improper  escaping

### ISSUE THREAD

**Issue by NicktheGeek** [theMikeD/add-seo-meta-tags#3]
https://github.com/theMikeD/add-seo-meta-tags/blob/master/add-seo-meta-tags.php#L908 is escaped incorrectly. It results in the HTML link being output as an escaped string.

This should be properly escaped without breaking the HTML link in the get text call.
```
		// Show message if nothing is enabled, then bail
		if ( ! in_array( '1', $global_values, true ) ) {
			?>
			<p>
				<?php
				printf(
					// translators: %1$s is replaced with the opening <a> tag with the href set to the options panel, %2$s is the closing <a> tag
					esc_html__( 'No SEO fields were enabled. Please enable post fields in the %1$s Meta Tags options page %2$s', 'add-meta-tags' ),
					'<a href="' . esc_url( get_admin_url() . 'options-general.php?page=' . $this->slug ) . '">',
					'</a>'
				);
				?>
			</p>
			<?php
			return;
		}
```

**Comment by theMikeD** [comment]
Thanks for the finding @NicktheGeek ! How does this look to you?

https://github.com/theMikeD/add-seo-meta-tags/pull/4

**Comment by NicktheGeek** [comment]
@theMikeD the kses approach works too.

**Comment by theMikeD** [comment]
I'm happy to hear if you think there's a better way :)

**Comment by NicktheGeek** [comment]
It works so it should be fine. Either solution will render the correct output and also continues to prevent XSS vectors. Beyond that it's more a style difference.
